# "STRATEGY": "base"
"STRATEGY": "random"
# "STRATEGY": "collab"
# "STRATEGY": "recollab"
"LR": 2.5e-4
"NUM_ENVS": 16
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 5e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"REW_SHAPING_HORIZON": 2.5e6
"ACTIVATION": "tanh"
"ENV_NAME": "overcooked"
"ENV_KWARGS": 
  "layout" : "cramped_room"
  # "layout" : "asymm_advantages"
  # "layout" : "coord_ring"
  "max_steps": 400
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 10
"SAVE_PATH": "/home/bhd445/projects/llm-agent-modeling/pretrained"
"RUBRIC_PATH": "/home/bhd445/projects/llm-agent-modeling/rubrics"
"DATABASE_PATH": "/home/bhd445/projects/llm-agent-modeling/databases"
"K": 20
"MODEL_ID": "openai:gpt-4o-mini"
"EMBEDDING_MODEL": "text-embedding-3-large"
"USE_ALL_TEAMMATES": True

# WandB Params
"ENTITY": "bhd445"
"PROJECT": "llm-overcooked"
"WANDB_MODE" : "online"
